name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Change permissions
        run: chmod 755 docs
      - name: Auto-i18n_translate
        env:
          # 设置环境变量
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          CHATGPT_API_BASE: ${{ secrets.CHATGPT_API_BASE }}
        run: |
          pip install openai
          python tools/auto-translater.py || true
      - name: Commit translated
        run: |
          git config --global user.email xxx@xx.com
          git config --global user.name xxx
          git add .
          git commit -m "Commit translated" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install MkDocs dependencies
        run: pip install -r requirements.txt
      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force
